### ISSUE TITLE
Error occurs when somebody broken in the game

### ISSUE THREAD

**Issue by mratoz** [mratoz/my-oop-cpp-richman#2]
Alice rolled 6
Alice location before rolling is: 0
Alice location after rolling is: 0
Dear Alice, you found No.0 land a virgin land. Do you want to buy?(Y/N):y
Alice, you have bought No.0 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 0, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 1000}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Bob rolled 3
Bob location before rolling is: 0
Bob location after rolling is: 3
Dear Bob, you found No.3 land a virgin land. Do you want to buy?(Y/N):y
Bob, you have bought No.3 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 3, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 0, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 1000}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Carl rolled 3
Carl location before rolling is: 0
Carl location after rolling is: 3
Carl paid 500 to Bob
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 3, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Dave rolled 4
Dave location before rolling is: 0
Dave location after rolling is: 4
Dear Dave, you found No.4 land a virgin land. Do you want to buy?(Y/N):y
Dave, you have bought No.4 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 3, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Alice rolled 2
Alice location before rolling is: 0
Alice location after rolling is: 2
Alice, sorry, No.2 land is not investable
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 3, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Bob rolled 4
Bob location before rolling is: 3
Bob location after rolling is: 1
Dear Bob, you found No.1 land a virgin land. Do you want to buy?(Y/N):y
Bob, you have bought No.1 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Carl rolled 2
Carl location before rolling is: 3
Carl location after rolling is: 5
Dear Carl, you found No.5 land a virgin land. Do you want to buy?(Y/N):y
Carl, you have bought No.5 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 0}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Dave rolled 6
Dave location before rolling is: 4
Dave location after rolling is: 4
Dear Dave, you have a chance to invest on No.4 land. Do you want it?(Y/N):y
Sorry, insufficient money for investment
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 0}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Alice rolled 3
Alice location before rolling is: 2
Alice location after rolling is: 5
Alice paid 500 to Carl
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 5, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Bob rolled 4
Bob location before rolling is: 1
Bob location after rolling is: 5
Bob paid 500 to Carl
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 5, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 5, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 1000}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Carl rolled 5
Carl location before rolling is: 5
Carl location after rolling is: 4
Carl paid 500 to Dave
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 5, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 5, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 4, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Dave rolled 5
Dave location before rolling is: 4
Dave location after rolling is: 3
Dave paid 500 to Bob
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 5, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 5, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 4, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 3, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Alice rolled 1
Alice location before rolling is: 5
Alice location after rolling is: 0
Dear Alice, you have a chance to invest on No.0 land. Do you want it?(Y/N):y
Sorry, insufficient money for investment
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 5, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 4, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 3, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Bob rolled 5
Bob location before rolling is: 5
Bob location after rolling is: 4
Bob paid 500 to Dave
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 4, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 4, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 3, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Carl rolled 1
Carl location before rolling is: 4
Carl location after rolling is: 5
Dear Carl, you have a chance to invest on No.5 land. Do you want it?(Y/N):y
Sorry, insufficient money for investment
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 4, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 3, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Dave rolled 4
Dave location before rolling is: 3
Dave location after rolling is: 1
Dave paid 500 to Bob
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 0, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 0}
1 : {'loc': 4, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 1, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Alice rolled 3
Alice location before rolling is: 0
Alice location after rolling is: 3
Alice paid 500 to Bob
Sorry, Alice, you are broken and quit the game.
                           Player Overview(3 in game)

In Game Players:
1 : {'loc': 4, 'prior': 3, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 5, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 1, 'prior': 2, 'next': 1, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Dave', 'owner': 3, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 5}
Traceback (most recent call last):
  File "py_richman.py", line 353, in <module>
    currentplayerid = players.WhoseTurn(lastplayer)
  File "py_richman.py", line 125, in WhoseTurn
    return self.GetProperty(i_lastplayerid, NEXT)
  File "py_richman.py", line 134, in GetProperty
    value = { None:self.playerlist[i_playerid],
KeyError: 0

**Comment by mratoz** [comment]
Aha, it accessed the broken player content, so it gives out error.

**Comment by mratoz** [comment]
Done with the code
