### ISSUE TITLE
You need to clear the building list after someone broken, otherwise, it will cause the access error

### ISSUE THREAD

**Issue by mratoz** [mratoz/my-oop-cpp-richman#3]
syn:2.code syn-ack$ python py_richman.py 
Alice rolled 4
Alice location before rolling is: 0
Alice location after rolling is: 4
Dear Alice, you found No.4 land a virgin land. Do you want to buy?(Y/N):y
Alice, you have bought No.4 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 1000}
2 : {'loc': 0, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 1000}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Bob rolled 6
Bob location before rolling is: 0
Bob location after rolling is: 0
Dear Bob, you found No.0 land a virgin land. Do you want to buy?(Y/N):y
Bob, you have bought No.0 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 0, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 1000}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Carl rolled 3
Carl location before rolling is: 0
Carl location after rolling is: 3
Dear Carl, you found No.3 land a virgin land. Do you want to buy?(Y/N):y
Carl, you have bought No.3 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 500}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 0, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 1000}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Dave rolled 4
Dave location before rolling is: 0
Dave location after rolling is: 4
Dave paid 500 to Alice
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 1000}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 0, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Alice rolled 6
Alice location before rolling is: 4
Alice location after rolling is: 4
Dear Alice, you have a chance to invest on No.4 land. Do you want it?(Y/N):y
Alice invested 750 to upgrade land 4
Upgrade finished and the building level reached 1
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 250.0}
1 : {'loc': 0, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 500}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Bob rolled 1
Bob location before rolling is: 0
Bob location after rolling is: 1
Dear Bob, you found No.1 land a virgin land. Do you want to buy?(Y/N):y
Bob, you have bought No.1 land
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 250.0}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Carl rolled 6
Carl location before rolling is: 3
Carl location after rolling is: 3
Dear Carl, you have a chance to invest on No.3 land. Do you want it?(Y/N):y
Sorry, insufficient money for investment
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 250.0}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 4, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Dave rolled 4
Dave location before rolling is: 4
Dave location after rolling is: 2
Dave, sorry, No.2 land is not investable
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 4, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 250.0}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 2, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Alice rolled 4
Alice location before rolling is: 4
Alice location after rolling is: 2
Alice, sorry, No.2 land is not investable
                           Player Overview(4 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 1, 'name': 'Alice', 'fund': 250.0}
1 : {'loc': 1, 'prior': 0, 'next': 2, 'name': 'Bob', 'fund': 0}
2 : {'loc': 3, 'prior': 1, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 2, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Bob rolled 3
Bob location before rolling is: 1
Bob location after rolling is: 4
Bob paid 500 to Alice
Sorry, Bob, you are broken and quit the game.
                           Player Overview(3 in game)

In Game Players:
0 : {'loc': 2, 'prior': 3, 'next': 2, 'name': 'Alice', 'fund': 750.0}
2 : {'loc': 3, 'prior': 0, 'next': 3, 'name': 'Carl', 'fund': 500}
3 : {'loc': 2, 'prior': 2, 'next': 0, 'name': 'Dave', 'fund': 500}
Map view:
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 0}
{'level': 0, 'value': 500, 'ownername': 'Bob', 'owner': 1, 'type': 0, 'id': 1}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 1, 'id': 2}
{'level': 0, 'value': 500, 'ownername': 'Carl', 'owner': 2, 'type': 0, 'id': 3}
{'level': 1, 'value': 500, 'ownername': 'Alice', 'owner': 0, 'type': 0, 'id': 4}
{'level': 0, 'value': 500, 'ownername': None, 'owner': None, 'type': 0, 'id': 5}
Carl rolled 4
Carl location before rolling is: 3
Carl location after rolling is: 1
Traceback (most recent call last):
  File "py_richman.py", line 360, in <module>
    players.DealTrans(currentplayerid, maps)
  File "py_richman.py", line 190, in DealTrans
    self.ChargeMoney(i_playerid, i_maplist)
  File "py_richman.py", line 219, in ChargeMoney
    ownername = self.GetProperty(ownerid, NAME)
  File "py_richman.py", line 137, in GetProperty
    value = { None:self.playerlist[i_playerid],
KeyError: 1

**Comment by mratoz** [comment]
Issue closed
